// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tum.PDE.ToolFramework.Templates
{
    using Tum.PDE.LanguageDSL;
    using Microsoft.VisualStudio.Modeling;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System;
    
    
    #line 1 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class SerializerGenerator : BaseTemplate
    {
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
        public override string TransformText()
        {
            this.GenerationEnvironment = null;
            this.Write(" \r\n");
            this.Write("using DslModeling = global::Microsoft.VisualStudio.Modeling;\r\nusing DslEditorMode" +
                    "ling = global::Tum.PDE.ToolFramework.Modeling;\r\n\r\n");
            
            #line 12 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

GenerateSerializer(this.MetaModel);

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 15 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
 
public void GenerateSerializer(MetaModel dm)
{
    DomainClass domainModel = null;
	foreach(DomainClass domainClass in dm.AllClasses)
	{
		if( domainClass.IsDomainModel )
		{
			domainModel = domainClass;
			break;
		}
	}
	
	List<KeyValuePair<AttributedDomainElement, string>> generatedSerializers = new List<KeyValuePair<AttributedDomainElement, string>>();
	IList<AttributedDomainElement> serializedClasses = CodeGenerationUtilities.GetSerializedDomainClasses(dm);
	
	foreach(AttributedDomainElement serializedClass in serializedClasses)
	{
		string s = DomainClassSerializer.Instance.GenerateDomainClassSerializer(serializedClass, dm.Namespace);
		if( s != null )
		{
			this.Write(s);
			string serializerTypeName = dm.Name + serializedClass.Name + "Serializer";
			if (!string.IsNullOrEmpty (serializerTypeName))
			{
				generatedSerializers.Add (new KeyValuePair<AttributedDomainElement, string> (serializedClass, serializerTypeName));
			}
		}
	}	

        
        #line default
        #line hidden
        
        #line 44 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("namespace ");

        
        #line default
        #line hidden
        
        #line 45 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Namespace));

        
        #line default
        #line hidden
        
        #line 45 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\r\n{\r\n\t/// <summary>\r\n\t/// A DomainXmlSerializationBehavior implementation for def" +
        "ined behavior ");

        
        #line default
        #line hidden
        
        #line 48 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 48 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior.\r\n\t/// This is the concrete type of the double-derived impl" +
        "ementation.\r\n\t/// </summary>\r\n\tpublic sealed partial class ");

        
        #line default
        #line hidden
        
        #line 51 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 51 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior : ");

        
        #line default
        #line hidden
        
        #line 51 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 51 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehaviorBase\r\n\t{\r\n\t\t#region Singleton Instance\r\n\t\t/// <summary>\r\n\t\t/" +
        "// Singleton instance.\r\n\t\t/// </summary>\r\n\t\tprivate static ");

        
        #line default
        #line hidden
        
        #line 57 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 57 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(@"SerializationBehavior instance;
	
		/// <summary>
		/// Singleton instance.
		/// </summary>
		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]	// Will trigger creation otherwise.
		public static ");

        
        #line default
        #line hidden
        
        #line 63 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 63 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior Instance\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\t// No need for synchronization." +
        " Most likely running in single-thread environment, and creating an extra instanc" +
        "e\r\n\t\t\t\t// doesn\'t really hurt.\r\n\t\t\t\tif (");

        
        #line default
        #line hidden
        
        #line 68 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 68 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior.instance == null)\r\n\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 69 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 69 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior.instance = new ");

        
        #line default
        #line hidden
        
        #line 69 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 69 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior ();\r\n\t\t\t\treturn ");

        
        #line default
        #line hidden
        
        #line 70 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 70 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior.instance;\r\n\t\t\t}\r\n\t\t}\r\n\t\r\n\t\t/// <summary>\r\n\t\t/// Private con" +
        "structor to prevent public instantiation.\r\n\t\t/// </summary>\r\n\t\tprivate ");

        
        #line default
        #line hidden
        
        #line 77 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 77 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior() : base() { }\r\n\t\t#endregion\r\n\t}\r\n\t\r\n\t/// <summary>\r\n\t/// A" +
        " DomainXmlSerializationBehavior implementation for defined behavior ");

        
        #line default
        #line hidden
        
        #line 82 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 82 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior.\r\n\t/// This is the abstract base of the double-derived impl" +
        "ementation.\r\n\t/// </summary>\r\n\tpublic abstract class ");

        
        #line default
        #line hidden
        
        #line 85 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 85 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehaviorBase : DslModeling::DomainXmlSerializationBehavior\r\n\t{\r\n\t\t//" +
        "/<summary>\r\n\t\t/// The xml namespace used by this domain model when serializing\r\n" +
        "\t\t///</summary>\r\n");

        
        #line default
        #line hidden
        
        #line 90 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

	if( domainModel != null )
	{

        
        #line default
        #line hidden
        
        #line 93 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\t\tpublic const string DomainModelXmlNamespace = @\"http://schemas.microsoft.com/ds" +
        "ltools/");

        
        #line default
        #line hidden
        
        #line 94 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(domainModel.Name));

        
        #line default
        #line hidden
        
        #line 94 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\";\r\n");

        
        #line default
        #line hidden
        
        #line 95 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

	}
	else
	{

        
        #line default
        #line hidden
        
        #line 99 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\t\tpublic const string DomainModelXmlNamespace = @\"http://schemas.microsoft.com/ds" +
        "ltools/");

        
        #line default
        #line hidden
        
        #line 100 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 100 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\";\r\n");

        
        #line default
        #line hidden
        
        #line 101 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

	}

        
        #line default
        #line hidden
        
        #line 103 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(@"		
		#region Member Variables
		/// <summary>
		/// A list of DomainClass Ids mapped to DomainClassXmlSerializer types.
		/// </summary>
		private static global::System.Collections.Generic.List<DslModeling::DomainXmlSerializerDirectoryEntry> serializerTypes;
	
		/// <summary>
		/// A list of xml namespaces mapped to domain model types.
		/// </summary>
		private static global::System.Collections.Generic.List<DslModeling::DomainXmlSerializerNamespaceEntry> namespaceEntries;
	
		#endregion
		
		#region Constructor
		/// <summary>
		/// Protected constructor to prevent public instantiation.
		/// </summary>
		protected ");

        
        #line default
        #line hidden
        
        #line 122 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 122 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(@"SerializationBehaviorBase() : base() { }
		#endregion
		
		#region Protected Methods
		/// <summary>
		/// Allows custom serializers to be added.
		/// Base implementation doesn't do anything.
		/// </summary>
		/// <returns>Custom serializer types, null or empty list if there's no custom serializer types.</returns>
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		protected virtual global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::DomainXmlSerializerDirectoryEntry> CustomSerializerTypes
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get { return null; }
		}
		#endregion
	
		#region Public Methods
		/// <summary>
		/// This provides a mapping from DomainClass Id to DomainXmlSerializer implementation types.
		/// </summary>
		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]	// Will trigger creation otherwise.
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage(""Microsoft.Maintainability"", ""CA1506:AvoidExcessiveClassCoupling"", Justification = ""Generated code."")]		
		public override global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::DomainXmlSerializerDirectoryEntry> AllSerializers
		{
			get
			{
				if (");

        
        #line default
        #line hidden
        
        #line 149 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 149 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(@"SerializationBehavior.serializerTypes == null)
				{
					global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::DomainXmlSerializerDirectoryEntry> customSerializerTypes = this.CustomSerializerTypes;
					int customSerializerCount = (customSerializerTypes == null ? 0 : customSerializerTypes.Count);
					");

        
        #line default
        #line hidden
        
        #line 153 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 153 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior.serializerTypes = new global::System.Collections.Generic.Li" +
        "st<DslModeling::DomainXmlSerializerDirectoryEntry>(");

        
        #line default
        #line hidden
        
        #line 153 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(generatedSerializers.Count));

        
        #line default
        #line hidden
        
        #line 153 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(" + customSerializerCount);\r\n\r\n\t\t\t\t\t#region Serializers defined in this model\r\n");

        
        #line default
        #line hidden
        
        #line 156 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

	foreach (KeyValuePair<AttributedDomainElement, string> pair in generatedSerializers)
	{

        
        #line default
        #line hidden
        
        #line 159 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 160 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 160 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior.serializerTypes.Add(new DslModeling::DomainXmlSerializerDir" +
        "ectoryEntry(");

        
        #line default
        #line hidden
        
        #line 160 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pair.Key.GetRelativeName(dm.Namespace, true)));

        
        #line default
        #line hidden
        
        #line 160 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(".DomainClassId, typeof(");

        
        #line default
        #line hidden
        
        #line 160 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(pair.Value));

        
        #line default
        #line hidden
        
        #line 160 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(")));\r\n");

        
        #line default
        #line hidden
        
        #line 161 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

	}

        
        #line default
        #line hidden
        
        #line 163 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\t\t\t\t\t#endregion\r\n\t\t\t\t\r\n\t\t\t\t\t#region Serializers of the diagram model defined in t" +
        "his model\r\n");

        
        #line default
        #line hidden
        
        #line 167 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

					foreach(DiagramClass diagram in this.MetaModel.AllDiagramClasses)
					{
						if( diagram is TemplatedDiagramViewModelOnly )
							continue;		

        
        #line default
        #line hidden
        
        #line 172 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 173 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 173 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior.serializerTypes.Add(new DslModeling::DomainXmlSerializerDir" +
        "ectoryEntry(");

        
        #line default
        #line hidden
        
        #line 173 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(diagram.Name));

        
        #line default
        #line hidden
        
        #line 173 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(".DomainClassId, typeof(");

        
        #line default
        #line hidden
        
        #line 173 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(this.MetaModel.Name));

        
        #line default
        #line hidden
        
        #line 173 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(diagram.Name));

        
        #line default
        #line hidden
        
        #line 173 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("Serializer)));\t\t\t\t\t\r\n");

        
        #line default
        #line hidden
        
        #line 174 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

						foreach (PresentationElementClass element in diagram.PresentationElements)
						{

        
        #line default
        #line hidden
        
        #line 177 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 178 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 178 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior.serializerTypes.Add(new DslModeling::DomainXmlSerializerDir" +
        "ectoryEntry(");

        
        #line default
        #line hidden
        
        #line 178 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(element.GetRelativeName(dm.Namespace, true)));

        
        #line default
        #line hidden
        
        #line 178 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(".DomainClassId, typeof(");

        
        #line default
        #line hidden
        
        #line 178 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(this.MetaModel.Name));

        
        #line default
        #line hidden
        
        #line 178 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(element.Name));

        
        #line default
        #line hidden
        
        #line 178 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("Serializer)));\t\t\t\t\t\r\n");

        
        #line default
        #line hidden
        
        #line 179 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

						}
					}

        
        #line default
        #line hidden
        
        #line 182 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\t\r\n\t\t\t\t\t#endregion\r\n\t\t\t\t\r\n\t\t\t\t\t// Custom ones\r\n\t\t\t\t\tif (customSerializerCount > 0" +
        ")\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 188 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 188 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior.serializerTypes.AddRange(customSerializerTypes);\r\n\t\t\t\t\t}\r\n\t" +
        "\t\t\t}\r\n\t\t\t\treturn ");

        
        #line default
        #line hidden
        
        #line 191 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 191 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(@"SerializationBehavior.serializerTypes.AsReadOnly();
			}
		}
		
		/// <summary>
		/// This provides a mapping from xml namespaces to domain model implementation types.
		/// </summary>
		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]	// Will trigger creation otherwise.
		public override global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::DomainXmlSerializerNamespaceEntry> AllNamespaces
		{
			get
			{
				if (");

        
        #line default
        #line hidden
        
        #line 203 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 203 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior.namespaceEntries == null)\r\n\t\t\t\t{\r\n\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 205 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 205 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior.namespaceEntries = new global::System.Collections.Generic.L" +
        "ist<DslModeling::DomainXmlSerializerNamespaceEntry>();\r\n\t\t\t\t}\r\n\t\t\t\treturn ");

        
        #line default
        #line hidden
        
        #line 207 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 207 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationBehavior.namespaceEntries.AsReadOnly();\r\n\t\t\t}\r\n\t\t}\r\n\t\t#endregion\r\n\t\t" +
        "\r\n\t\t#region Public Virtual Properties\r\n");

        
        #line default
        #line hidden
        
        #line 213 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

		foreach(BaseModelContext m in dm.ModelContexts)
		{
			if( m is LibraryModelContext)
			{

        
        #line default
        #line hidden
        
        #line 218 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\t\t/// <summary>\r\n        /// Id-Serialization name.\r\n        /// </summary>\r\n\t\tpu" +
        "blic virtual string IdSerializationName");

        
        #line default
        #line hidden
        
        #line 222 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(m.Name));

        
        #line default
        #line hidden
        
        #line 222 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\r\n\t\t{\r\n\t\t\tget{ return \"");

        
        #line default
        #line hidden
        
        #line 224 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture((m as LibraryModelContext).SerializationModel.SerializedIdAttributeName));

        
        #line default
        #line hidden
        
        #line 224 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\"; }\r\n\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 226 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

			}
		}

        
        #line default
        #line hidden
        
        #line 229 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\t\t#endregion\r\n\t}\r\n}\r\n\r\nnamespace ");

        
        #line default
        #line hidden
        
        #line 234 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Namespace));

        
        #line default
        #line hidden
        
        #line 234 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\r\n{\r\n    /// <summary>\r\n    /// Utility class to provide serialization messages\r\n" +
        "    /// </summary>\r\n    public static partial class ");

        
        #line default
        #line hidden
        
        #line 239 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 239 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(@"SerializationBehaviorSerializationMessages
    {
    	/// <summary>
    	/// ResourceManager to get serialization messages from.
    	/// </summary>
    	[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)] // Will trigger creation otherwise.
    	public static global::System.Resources.ResourceManager ResourceManager
    	{
    		[global::System.Diagnostics.DebuggerStepThrough]
    		get { return ");

        
        #line default
        #line hidden
        
        #line 248 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 248 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("DomainModel.SingletonResourceManager; }\r\n    \t}\r\n\r\n    \t#region Warnings\r\n    \t//" +
        "/ <summary>\r\n    \t/// Add a warning for ambiguous schemas.\r\n    \t/// </summary>\r" +
        "\n    \t/// <param name=\"serializationContext\">SerializationContext to add the war" +
        "ning message to.</param>\r\n    \t/// <param name=\"reader\">The reader pointing to w" +
        "here the message is raised.</param>\r\n    \t/// <param name=\"targetNamespace\">Targ" +
        "et namespace to be resolved.</param>\r\n    \t/// <param name=\"schemaPath\">The sche" +
        "ma that is used to resolve the definition of the target namespace.</param>\r\n    " +
        "\tpublic static void AmbiguousSchema(DslModeling::SerializationContext serializat" +
        "ionContext, global::System.Xml.XmlReader reader, string targetNamespace, string " +
        "schemaPath)\r\n    \t{\r\n    \t\t#region Check Parameters\r\n    \t\tglobal::System.Diagno" +
        "stics.Debug.Assert(serializationContext != null);\r\n    \t\tif (serializationContex" +
        "t == null)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"serialization" +
        "Context\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(reader != null);\r\n    " +
        "\t\tif (reader == null)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"re" +
        "ader\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(!string.IsNullOrEmpty(tar" +
        "getNamespace));\r\n    \t\tif (string.IsNullOrEmpty(targetNamespace))\r\n    \t\t\tthrow " +
        "new global::System.ArgumentNullException(\"targetNamespace\");\r\n    \t\tglobal::Syst" +
        "em.Diagnostics.Debug.Assert(!string.IsNullOrEmpty(schemaPath));\r\n    \t\tif (strin" +
        "g.IsNullOrEmpty(schemaPath))\r\n    \t\t\tthrow new global::System.ArgumentNullExcept" +
        "ion(\"schemaPath\");\r\n    \t\t#endregion\r\n\r\n    \t\tDslModeling::SerializationUtilitie" +
        "s.AddMessage(\r\n    \t\t\tserializationContext,\r\n    \t\t\tDslModeling::SerializationMe" +
        "ssageKind.Warning,\r\n    \t\t\tstring.Format(\r\n    \t\t\t\tglobal::System.Globalization." +
        "CultureInfo.CurrentCulture,\r\n    \t\t\t\tResourceManager.GetString(\"AmbiguousSchema\"" +
        "),\r\n    \t\t\t\ttargetNamespace,\r\n    \t\t\t\tschemaPath\r\n    \t\t\t),\r\n    \t\t\treader as gl" +
        "obal::System.Xml.IXmlLineInfo\r\n    \t\t);\r\n    \t}\r\n    \t\r\n    \t/// <summary>\r\n    " +
        "\t/// Add a warning when a full-form relationship seems to be serialized in short" +
        "-form.\r\n    \t/// </summary>\r\n    \t/// <param name=\"serializationContext\">Seriali" +
        "zationContext to add the warning message to.</param>\r\n    \t/// <param name=\"read" +
        "er\">The reader pointing to where the message is raised.</param>\r\n    \t/// <param" +
        " name=\"relationshipType\">Type of the relationship.</param>\r\n    \t[global::System" +
        ".Diagnostics.CodeAnalysis.SuppressMessage(\"Microsoft.Design\", \"CA1011:ConsiderPa" +
        "ssingBaseTypesAsParameters\", Justification = \"This is the type of the relationsh" +
        "ip, making it MemberInfo only adds confusion.\")]\r\n    \tpublic static void Expect" +
        "ingFullFormRelationship(DslModeling::SerializationContext serializationContext, " +
        "global::System.Xml.XmlReader reader, global::System.Type relationshipType)\r\n    " +
        "\t{\r\n    \t\t#region Check Parameters\r\n    \t\tglobal::System.Diagnostics.Debug.Asser" +
        "t(serializationContext != null);\r\n    \t\tif (serializationContext == null)\r\n    \t" +
        "\t\tthrow new global::System.ArgumentNullException(\"serializationContext\");\r\n    \t" +
        "\tglobal::System.Diagnostics.Debug.Assert(reader != null);\r\n    \t\tif (reader == n" +
        "ull)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"reader\");\r\n    \t\tgl" +
        "obal::System.Diagnostics.Debug.Assert(relationshipType != null);\r\n    \t\tif (rela" +
        "tionshipType == null)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"re" +
        "lationshipType\");\r\n    \t\t#endregion\r\n    \t\t\r\n    \t\tDslModeling::SerializationUti" +
        "lities.AddMessage(\r\n    \t\t\tserializationContext,\r\n    \t\t\tDslModeling::Serializat" +
        "ionMessageKind.Warning,\r\n    \t\t\tstring.Format(\r\n    \t\t\t\tglobal::System.Globaliza" +
        "tion.CultureInfo.CurrentCulture,\r\n    \t\t\t\tResourceManager.GetString(\"ExpectingFu" +
        "llFormRelationship\"),\r\n    \t\t\t\treader.Name,\r\n    \t\t\t\trelationshipType.Name\r\n    " +
        "\t\t\t),\r\n    \t\t\treader as global::System.Xml.IXmlLineInfo\r\n    \t\t);\r\n    \t}\r\n    \t" +
        "\r\n    \t/// <summary>\r\n    \t/// Add a warning when a short-form relationship seem" +
        "s to be serialized in full-form.\r\n    \t/// </summary>\r\n    \t/// <param name=\"ser" +
        "ializationContext\">SerializationContext to add the warning message to.</param>\r\n" +
        "    \t/// <param name=\"reader\">The reader pointing to where the message is raised" +
        ".</param>\r\n    \t/// <param name=\"relationshipType\">Type of the relationship.</pa" +
        "ram>\r\n    \t[global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Microsoft.D" +
        "esign\", \"CA1011:ConsiderPassingBaseTypesAsParameters\", Justification = \"This is " +
        "the type of the relationship, making it MemberInfo only adds confusion.\")]\r\n    " +
        "\tpublic static void ExpectingShortFormRelationship(DslModeling::SerializationCon" +
        "text serializationContext, global::System.Xml.XmlReader reader, global::System.T" +
        "ype relationshipType)\r\n    \t{\r\n    \t\t#region Check Parameters\r\n    \t\tglobal::Sys" +
        "tem.Diagnostics.Debug.Assert(serializationContext != null);\r\n    \t\tif (serializa" +
        "tionContext == null)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"ser" +
        "ializationContext\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(reader != nu" +
        "ll);\r\n    \t\tif (reader == null)\r\n    \t\t\tthrow new global::System.ArgumentNullExc" +
        "eption(\"reader\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(relationshipTyp" +
        "e != null);\r\n    \t\tif (relationshipType == null)\r\n    \t\t\tthrow new global::Syste" +
        "m.ArgumentNullException(\"relationshipType\");\r\n    \t\t#endregion\r\n    \t\t\r\n    \t\tDs" +
        "lModeling::SerializationUtilities.AddMessage(\r\n    \t\t\tserializationContext,\r\n   " +
        " \t\t\tDslModeling::SerializationMessageKind.Warning,\r\n    \t\t\tstring.Format(\r\n    \t" +
        "\t\t\tglobal::System.Globalization.CultureInfo.CurrentCulture,\r\n    \t\t\t\tResourceMan" +
        "ager.GetString(\"ExpectingShortFormRelationship\"),\r\n    \t\t\t\trelationshipType.Name" +
        "\r\n    \t\t\t),\r\n    \t\t\treader as global::System.Xml.IXmlLineInfo\r\n    \t\t);\r\n    \t}\r" +
        "\n    \t\r\n    \t/// <summary>\r\n    \t/// Add a warning for invalid property value wi" +
        "th the given type, which will be ignored.\r\n    \t/// </summary>\r\n    \t/// <param " +
        "name=\"serializationContext\">SerializationContext to add the warning message to.<" +
        "/param>\r\n    \t/// <param name=\"reader\">The reader pointing to where the message " +
        "is raised.</param>\r\n    \t/// <param name=\"propertyName\">Name of the property.</p" +
        "aram>\r\n    \t/// <param name=\"propertyType\">Type of the property.</param>\r\n    \t/" +
        "// <param name=\"value\">Invalid value that causes this warning.</param>\r\n    \t[gl" +
        "obal::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Microsoft.Design\", \"CA101" +
        "1:ConsiderPassingBaseTypesAsParameters\", Justification = \"This is the type of th" +
        "e property, making it MemberInfo only adds confusion.\")]\r\n    \tpublic static voi" +
        "d IgnoredPropertyValue(DslModeling::SerializationContext serializationContext, g" +
        "lobal::System.Xml.XmlReader reader, string propertyName, global::System.Type pro" +
        "pertyType, string value)\r\n    \t{\r\n    \t\t#region Check Parameters\r\n    \t\tglobal::" +
        "System.Diagnostics.Debug.Assert(serializationContext != null);\r\n    \t\tif (serial" +
        "izationContext == null)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"" +
        "serializationContext\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(reader !=" +
        " null);\r\n    \t\tif (reader == null)\r\n    \t\t\tthrow new global::System.ArgumentNull" +
        "Exception(\"reader\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(propertyType" +
        " != null);\r\n    \t\tif (propertyType == null)\r\n    \t\t\tthrow new global::System.Arg" +
        "umentNullException(\"propertyType\");\r\n    \t\tglobal::System.Diagnostics.Debug.Asse" +
        "rt(!string.IsNullOrEmpty(propertyName));\r\n    \t\tif (string.IsNullOrEmpty(propert" +
        "yName))\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"propertyName\");\r" +
        "\n    \t\t#endregion\r\n    \t\t\r\n    \t\tif (value == null)\r\n    \t\t\tvalue = \"<null>\";\r\n\r" +
        "\n    \t\tDslModeling::SerializationUtilities.AddMessage(\r\n    \t\t\tserializationCont" +
        "ext,\r\n    \t\t\tDslModeling::SerializationMessageKind.Warning,\r\n    \t\t\tstring.Forma" +
        "t(\r\n    \t\t\t\tglobal::System.Globalization.CultureInfo.CurrentCulture,\r\n    \t\t\t\tRe" +
        "sourceManager.GetString(\"IgnoredPropertyValue\"),\r\n    \t\t\t\tvalue,\r\n    \t\t\t\tproper" +
        "tyName,\r\n    \t\t\t\tpropertyType.Name\r\n    \t\t\t),\r\n    \t\t\treader as global::System.X" +
        "ml.IXmlLineInfo\r\n    \t\t);\r\n    \t}\r\n    \t\r\n    \t/// <summary>\r\n    \t/// Add a war" +
        "ning for missing \"Id\" property.\r\n    \t/// </summary>\r\n    \t/// <param name=\"seri" +
        "alizationContext\">SerializationContext to add the warning message to.</param>\r\n " +
        "   \t/// <param name=\"reader\">The reader pointing to where the message is raised." +
        "</param>\r\n    \t/// <param name=\"newId\">Auto-generated new Id.</param>\r\n    \tpubl" +
        "ic static void MissingId(DslModeling::SerializationContext serializationContext," +
        " global::System.Xml.XmlReader reader, global::System.Guid newId)\r\n    \t{\r\n    \t\t" +
        "#region Check Parameters\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(serializ" +
        "ationContext != null);\r\n    \t\tif (serializationContext == null)\r\n    \t\t\tthrow ne" +
        "w global::System.ArgumentNullException(\"serializationContext\");\r\n    \t\tglobal::S" +
        "ystem.Diagnostics.Debug.Assert(reader != null);\r\n    \t\tif (reader == null)\r\n    " +
        "\t\t\tthrow new global::System.ArgumentNullException(\"reader\");\r\n    \t\t#endregion\r\n" +
        "    \t\t\r\n    \t\tDslModeling::SerializationUtilities.AddMessage(\r\n    \t\t\tserializat" +
        "ionContext,\r\n    \t\t\tDslModeling::SerializationMessageKind.Warning,\r\n    \t\t\tstrin" +
        "g.Format(\r\n    \t\t\t\tglobal::System.Globalization.CultureInfo.CurrentCulture,\r\n   " +
        " \t\t\t\tResourceManager.GetString(\"MissingId\"),\r\n    \t\t\t\tnewId.ToString(\"D\", global" +
        "::System.Globalization.CultureInfo.CurrentCulture)\r\n    \t\t\t),\r\n    \t\t\treader as " +
        "global::System.Xml.IXmlLineInfo\r\n    \t\t);\r\n    \t}\r\n    \t\r\n    \t\t\r\n    \t/// <summ" +
        "ary>\r\n    \t/// Add an warning for moniker resolved to duplicate link. The monike" +
        "r will be ignored.\r\n    \t/// </summary>\r\n    \t/// <param name=\"serializationResu" +
        "lt\">SerializationResult to add the error message to.</param>\r\n    \t/// <param na" +
        "me=\"moniker\">Offending moniker.</param>\r\n    \tpublic static void MonikerResolved" +
        "ToDuplicateLink(DslModeling::SerializationResult serializationResult, DslModelin" +
        "g::Moniker moniker)\r\n    \t{\r\n    \t\t#region Check Parameters\r\n    \t\tglobal::Syste" +
        "m.Diagnostics.Debug.Assert(serializationResult != null);\r\n    \t\tif (serializatio" +
        "nResult == null)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"seriali" +
        "zationResult\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(moniker != null);" +
        "\r\n    \t\tif (moniker == null)\r\n    \t\t\tthrow new global::System.ArgumentNullExcept" +
        "ion(\"moniker\");\r\n    \t\t#endregion\r\n    \t\t\r\n    \t\tDslModeling::SerializationUtili" +
        "ties.AddMessage(\r\n    \t\t\tserializationResult,\r\n    \t\t\tmoniker.Location,\r\n    \t\t\t" +
        "DslModeling::SerializationMessageKind.Warning,\r\n    \t\t\tstring.Format(\r\n    \t\t\t\tg" +
        "lobal::System.Globalization.CultureInfo.CurrentCulture,\r\n    \t\t\t\tResourceManager" +
        ".GetString(\"MonikerResolvedToDuplicateLink\"),\r\n    \t\t\t\tmoniker.MonikerName\r\n    " +
        "\t\t\t),\r\n    \t\t\tmoniker.Line,\r\n    \t\t\tmoniker.Column\r\n    \t\t);\r\n    \t}\r\n    \t\r\n   " +
        " \t/// <summary>\r\n    \t/// Add a warning for no schema found for the given target" +
        " namespace, schema validation will be skipped in this case.\r\n    \t/// </summary>" +
        "\r\n    \t/// <param name=\"serializationContext\">SerializationContext to add the wa" +
        "rning message to.</param>\r\n    \t/// <param name=\"reader\">The reader pointing to " +
        "where the message is raised.</param>\r\n    \t/// <param name=\"targetNamespace\">Tar" +
        "get namespace that cannot be resolved.</param>\r\n    \tpublic static void NoSchema" +
        "(DslModeling::SerializationContext serializationContext, global::System.Xml.XmlR" +
        "eader reader, string targetNamespace)\r\n    \t{\r\n    \t\t#region Check Parameters\r\n " +
        "   \t\tglobal::System.Diagnostics.Debug.Assert(serializationContext != null);\r\n   " +
        " \t\tif (serializationContext == null)\r\n    \t\t\tthrow new global::System.ArgumentNu" +
        "llException(\"serializationContext\");\r\n    \t\tglobal::System.Diagnostics.Debug.Ass" +
        "ert(reader != null);\r\n    \t\tif (reader == null)\r\n    \t\t\tthrow new global::System" +
        ".ArgumentNullException(\"reader\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert" +
        "(!string.IsNullOrEmpty(targetNamespace));\r\n    \t\tif (string.IsNullOrEmpty(target" +
        "Namespace))\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"targetNamesp" +
        "ace\");\r\n    \t\t#endregion\r\n\r\n    \t\tDslModeling::SerializationUtilities.AddMessage" +
        "(\r\n    \t\t\tserializationContext,\r\n    \t\t\tDslModeling::SerializationMessageKind.Wa" +
        "rning,\r\n    \t\t\tstring.Format(\r\n    \t\t\t\tglobal::System.Globalization.CultureInfo." +
        "CurrentCulture,\r\n    \t\t\t\tResourceManager.GetString(\"NoSchema\"),\r\n    \t\t\t\ttargetN" +
        "amespace\r\n    \t\t\t),\r\n    \t\t\treader as global::System.Xml.IXmlLineInfo\r\n    \t\t);\r" +
        "\n    \t}\r\n    \t\r\n    \t/// <summary>\r\n    \t/// Add a warning for schema validation" +
        " error.\r\n    \t/// </summary>\r\n    \t/// <param name=\"serializationContext\">Serial" +
        "izationContext to add the warning message to.</param>\r\n    \t/// <param name=\"rea" +
        "der\">The reader pointing to where the message is raised.</param>\r\n    \t/// <para" +
        "m name=\"message\">Validation message reported from schema validation.</param>\r\n  " +
        "  \tpublic static void SchemaValidationError(DslModeling::SerializationContext se" +
        "rializationContext, global::System.Xml.XmlReader reader, string message)\r\n    \t{" +
        "\r\n    \t\t#region Check Parameters\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(" +
        "serializationContext != null);\r\n    \t\tif (serializationContext == null)\r\n    \t\t\t" +
        "throw new global::System.ArgumentNullException(\"serializationContext\");\r\n    \t\tg" +
        "lobal::System.Diagnostics.Debug.Assert(reader != null);\r\n    \t\tif (reader == nul" +
        "l)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"reader\");\r\n    \t\tglob" +
        "al::System.Diagnostics.Debug.Assert(!string.IsNullOrEmpty(message));\r\n    \t\tif (" +
        "string.IsNullOrEmpty(message))\r\n    \t\t\tthrow new global::System.ArgumentNullExce" +
        "ption(\"message\");\r\n    \t\t#endregion\r\n\r\n    \t\tDslModeling::SerializationUtilities" +
        ".AddMessage(\r\n    \t\t\tserializationContext,\r\n    \t\t\tDslModeling::SerializationMes" +
        "sageKind.Warning,\r\n    \t\t\tmessage,\r\n    \t\t\treader as global::System.Xml.IXmlLine" +
        "Info\r\n    \t\t);\r\n    \t}\r\n    \t\r\n    \t/// <summary>\r\n    \t/// Add an warning for u" +
        "nexpected XML element.\r\n    \t/// </summary>\r\n    \t/// <param name=\"serialization" +
        "Context\">SerializationContext to add the warning message to.</param>\r\n    \t/// <" +
        "param name=\"reader\">The reader pointing to where the message is raised.</param>\r" +
        "\n\t\t/// <param name=\"parentName\"></param>\r\n    \tpublic static void UnexpectedXmlE" +
        "lement(DslModeling::SerializationContext serializationContext, global::System.Xm" +
        "l.XmlReader reader, string parentName)\r\n    \t{\r\n    \t\t#region Check Parameters\r\n" +
        "    \t\tglobal::System.Diagnostics.Debug.Assert(serializationContext != null);\r\n  " +
        "  \t\tif (serializationContext == null)\r\n    \t\t\tthrow new global::System.ArgumentN" +
        "ullException(\"serializationContext\");\r\n    \t\tglobal::System.Diagnostics.Debug.As" +
        "sert(reader != null);\r\n    \t\tif (reader == null)\r\n    \t\t\tthrow new global::Syste" +
        "m.ArgumentNullException(\"reader\");\r\n    \t\t#endregion\r\n    \t\t\t\r\n    \t\tDslModeling" +
        "::SerializationUtilities.AddMessage(\r\n    \t\t\tserializationContext,\r\n    \t\t\tDslMo" +
        "deling::SerializationMessageKind.Warning,\r\n    \t\t\tstring.Format(\r\n    \t\t\t\tglobal" +
        "::System.Globalization.CultureInfo.CurrentCulture,\r\n    \t\t\t\tResourceManager.GetS" +
        "tring(\"UnexpectedXmlElement\"),\r\n    \t\t\t\treader.Name\r\n    \t\t\t) + \" Parent:\" + par" +
        "entName,\r\n    \t\t\treader as global::System.Xml.IXmlLineInfo\r\n    \t\t);\r\n    \t}\r\n  " +
        "  \t#endregion\r\n\r\n    \t#region Errors\r\n    \t/// <summary>\r\n    \t/// Add an error " +
        "for ambiguous moniker.\r\n    \t/// </summary>\r\n    \t/// <param name=\"serialization" +
        "Context\">SerializationContext to add the error message to.</param>\r\n    \t/// <pa" +
        "ram name=\"moniker\">The ambiguous moniker string.</param>\r\n    \t/// <param name=\"" +
        "element1\">The first element using the given moniker.</param>\r\n    \t/// <param na" +
        "me=\"element2\">The second element using the given moniker.</param>\r\n    \tpublic s" +
        "tatic void AmbiguousMoniker(DslModeling::SerializationContext serializationConte" +
        "xt, string moniker, DslModeling::ModelElement element1, DslModeling::ModelElemen" +
        "t element2)\r\n    \t{\r\n    \t\t#region Check Parameters\r\n    \t\tglobal::System.Diagno" +
        "stics.Debug.Assert(serializationContext != null);\r\n    \t\tif (serializationContex" +
        "t == null)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"serialization" +
        "Context\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(moniker != null);\r\n   " +
        " \t\tif (moniker == null)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"" +
        "moniker\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(element1 != null);\r\n  " +
        "  \t\tif (element1 == null)\r\n    \t\t\tthrow new global::System.ArgumentNullException" +
        "(\"element1\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(element2 != null);\r" +
        "\n    \t\tif (element2 == null)\r\n    \t\t\tthrow new global::System.ArgumentNullExcept" +
        "ion(\"element2\");\r\n    \t\t#endregion\r\n\r\n    \t\tDslModeling::SerializationUtilities." +
        "AddMessage(\r\n    \t\t\tserializationContext,\r\n    \t\t\tDslModeling::SerializationMess" +
        "ageKind.Error,\r\n    \t\t\tstring.Format(\r\n    \t\t\t\tglobal::System.Globalization.Cult" +
        "ureInfo.CurrentCulture,\r\n    \t\t\t\tResourceManager.GetString(\"AmbiguousMoniker\"),\r" +
        "\n    \t\t\t\tmoniker,\r\n    \t\t\t\tDslModeling::SerializationUtilities.GetElementName(el" +
        "ement1),\r\n    \t\t\t\tDslModeling::SerializationUtilities.GetElementName(element2)\r\n" +
        "    \t\t\t),\r\n    \t\t\tnull\t// No location info available\r\n    \t\t);\r\n    \t}\r\n    \t\r\n " +
        "   \t/// <summary>\r\n    \t/// Add an error for not able to monikerize an instance " +
        "of the given DomainClass.\r\n    \t/// </summary>\r\n    \t/// <param name=\"serializat" +
        "ionContext\">SerializationContext to add the error message to.</param>\r\n    \t/// " +
        "<param name=\"domainClassName\">Name of the DomainClass whose instance cannot be m" +
        "onikerized.</param>\r\n    \t[global::System.Diagnostics.CodeAnalysis.SuppressMessa" +
        "ge(\"Microsoft.Naming\", \"CA1704:IdentifiersShouldBeSpelledCorrectly\", Justificati" +
        "on = \"Generated code.\")]\t\r\n    \tpublic static void CannotMonikerizeElement(DslMo" +
        "deling::SerializationContext serializationContext, string domainClassName)\r\n    " +
        "\t{\r\n    \t\t#region Check Parameters\r\n    \t\tglobal::System.Diagnostics.Debug.Asser" +
        "t(serializationContext != null);\r\n    \t\tif (serializationContext == null)\r\n    \t" +
        "\t\tthrow new global::System.ArgumentNullException(\"serializationContext\");\r\n    \t" +
        "\tglobal::System.Diagnostics.Debug.Assert(!string.IsNullOrEmpty(domainClassName))" +
        ";\r\n    \t\tif (string.IsNullOrEmpty(domainClassName))\r\n    \t\t\tthrow new global::Sy" +
        "stem.ArgumentNullException(\"domainClassName\");\r\n    \t\t#endregion\r\n    \t\t\r\n    \t\t" +
        "DslModeling::SerializationUtilities.AddMessage(\r\n    \t\t\tserializationContext.Res" +
        "ult,\r\n    \t\t\tnull,\t/* no location available for this error, because save failed." +
        " */\r\n    \t\t\tDslModeling::SerializationMessageKind.Error,\r\n    \t\t\tstring.Format(\r" +
        "\n    \t\t\t\tglobal::System.Globalization.CultureInfo.CurrentCulture,\r\n    \t\t\t\tResou" +
        "rceManager.GetString(\"CannotMonikerizeElement\"),\r\n    \t\t\t\tdomainClassName\r\n    \t" +
        "\t\t),\r\n    \t\t\t0,\r\n    \t\t\t0\r\n    \t\t);\r\n    \t}\r\n    \t\r\n    \t/// <summary>\r\n    \t///" +
        " Add an error for dangling relationship instance.\r\n    \t/// </summary>\r\n    \t///" +
        " <param name=\"serializationContext\">SerializationContext to add the error messag" +
        "e to.</param>\r\n    \t/// <param name=\"reader\">The reader pointing to where the me" +
        "ssage is raised.</param>\r\n    \t/// <param name=\"relationshipType\">Type name of t" +
        "he relationship.</param>\r\n    \tpublic static void DanglingRelationship(DslModeli" +
        "ng::SerializationContext serializationContext, global::System.Xml.XmlReader read" +
        "er, string relationshipType)\r\n    \t{\r\n    \t\t#region Check Parameters\r\n    \t\tglob" +
        "al::System.Diagnostics.Debug.Assert(serializationContext != null);\r\n    \t\tif (se" +
        "rializationContext == null)\r\n    \t\t\tthrow new global::System.ArgumentNullExcepti" +
        "on(\"serializationContext\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(reade" +
        "r != null);\r\n    \t\tif (reader == null)\r\n    \t\t\tthrow new global::System.Argument" +
        "NullException(\"reader\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(!string." +
        "IsNullOrEmpty(relationshipType));\r\n    \t\tif (string.IsNullOrEmpty(relationshipTy" +
        "pe))\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"relationshipType\");" +
        "\r\n    \t\t#endregion\r\n    \t\t\r\n    \t\tDslModeling::SerializationUtilities.AddMessage" +
        "(\r\n    \t\t\tserializationContext,\r\n    \t\t\tDslModeling::SerializationMessageKind.Er" +
        "ror,\r\n    \t\t\tstring.Format(\r\n    \t\t\t\tglobal::System.Globalization.CultureInfo.Cu" +
        "rrentCulture,\r\n    \t\t\t\tResourceManager.GetString(\"DanglingRelationship\"),\r\n    \t" +
        "\t\t\trelationshipType\r\n    \t\t\t),\r\n    \t\t\treader as global::System.Xml.IXmlLineInfo" +
        "\r\n    \t\t);\r\n    \t}\r\n    \t\r\n    \t/// <summary>\r\n    \t/// Add an error for invalid" +
        " property value with given type.\r\n    \t/// </summary>\r\n    \t/// <param name=\"ser" +
        "ializationContext\">SerializationContext to add the error message to.</param>\r\n  " +
        "  \t/// <param name=\"reader\">The reader pointing to where the message is raised.<" +
        "/param>\r\n    \t/// <param name=\"propertyName\">Name of the property.</param>\r\n    " +
        "\t/// <param name=\"propertyType\">Type of the property.</param>\r\n    \t/// <param n" +
        "ame=\"value\">Invalid value that causes this error.</param>\r\n    \t[global::System." +
        "Diagnostics.CodeAnalysis.SuppressMessage(\"Microsoft.Design\", \"CA1011:ConsiderPas" +
        "singBaseTypesAsParameters\", Justification = \"This is the type of the property, m" +
        "aking it MemberInfo only adds confusion.\")]\r\n    \tpublic static void InvalidProp" +
        "ertyValue(DslModeling::SerializationContext serializationContext, global::System" +
        ".Xml.XmlReader reader, string propertyName, global::System.Type propertyType, st" +
        "ring value)\r\n    \t{\r\n    \t\t#region Check Parameters\r\n    \t\tglobal::System.Diagno" +
        "stics.Debug.Assert(serializationContext != null);\r\n    \t\tif (serializationContex" +
        "t == null)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"serialization" +
        "Context\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(reader != null);\r\n    " +
        "\t\tif (reader == null)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"re" +
        "ader\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(propertyType != null);\r\n " +
        "   \t\tif (propertyType == null)\r\n    \t\t\tthrow new global::System.ArgumentNullExce" +
        "ption(\"propertyType\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(!string.Is" +
        "NullOrEmpty(propertyName));\r\n    \t\tif (string.IsNullOrEmpty(propertyName))\r\n    " +
        "\t\t\tthrow new global::System.ArgumentNullException(\"propertyName\");\r\n    \t\t#endre" +
        "gion\r\n    \t\t\r\n    \t\tif (value == null)\r\n    \t\t\tvalue = \"<null>\";\r\n\r\n    \t\tDslMod" +
        "eling::SerializationUtilities.AddMessage(\r\n    \t\t\tserializationContext,\r\n    \t\t\t" +
        "DslModeling::SerializationMessageKind.Error,\r\n    \t\t\tstring.Format(\r\n    \t\t\t\tglo" +
        "bal::System.Globalization.CultureInfo.CurrentCulture,\r\n    \t\t\t\tResourceManager.G" +
        "etString(\"InvalidPropertyValue\"),\r\n    \t\t\t\tvalue,\r\n    \t\t\t\tpropertyName,\r\n    \t\t" +
        "\t\tpropertyType.Name\r\n    \t\t\t),\r\n    \t\t\treader as global::System.Xml.IXmlLineInfo" +
        "\r\n    \t\t);\r\n    \t}\r\n    \t\r\n    \t/// <summary>\r\n    \t/// Add an error for missing" +
        " moniker.\r\n    \t/// </summary>\r\n    \t/// <param name=\"serializationContext\">Seri" +
        "alizationContext to add the error message to.</param>\r\n    \t/// <param name=\"rea" +
        "der\">The reader pointing to where the message is raised.</param>\r\n    \t/// <para" +
        "m name=\"monikerAttributeName\">Name of the attribute that should hold the moniker" +
        ".</param>\r\n    \tpublic static void MissingMoniker(DslModeling::SerializationCont" +
        "ext serializationContext, global::System.Xml.XmlReader reader, string monikerAtt" +
        "ributeName)\r\n    \t{\r\n    \t\t#region Check Parameters\r\n    \t\tglobal::System.Diagno" +
        "stics.Debug.Assert(serializationContext != null);\r\n    \t\tif (serializationContex" +
        "t == null)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"serialization" +
        "Context\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(reader != null);\r\n    " +
        "\t\tif (reader == null)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"re" +
        "ader\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(!string.IsNullOrEmpty(mon" +
        "ikerAttributeName));\r\n    \t\tif (string.IsNullOrEmpty(monikerAttributeName))\r\n   " +
        " \t\t\tthrow new global::System.ArgumentNullException(\"monikerAttributeName\");\r\n   " +
        " \t\t#endregion\r\n    \t\t\r\n    \t\tDslModeling::SerializationUtilities.AddMessage(\r\n  " +
        "  \t\t\tserializationContext,\r\n    \t\t\tDslModeling::SerializationMessageKind.Error,\r" +
        "\n    \t\t\tstring.Format(\r\n    \t\t\t\tglobal::System.Globalization.CultureInfo.Current" +
        "Culture,\r\n    \t\t\t\tResourceManager.GetString(\"MissingMoniker\"),\r\n    \t\t\t\tmonikerA" +
        "ttributeName\r\n    \t\t\t),\r\n    \t\t\treader as global::System.Xml.IXmlLineInfo\r\n    \t" +
        "\t);\r\n    \t}\r\n    \t\r\n    \t/// <summary>\r\n    \t/// Add an error for unresolved mon" +
        "iker.\r\n    \t/// </summary>\r\n    \t/// <param name=\"serializationResult\">Serializa" +
        "tionResult to add the error message to.</param>\r\n    \t/// <param name=\"moniker\">" +
        "Unresolved moniker.</param>\r\n    \tpublic static void UnresolvedMoniker(DslModeli" +
        "ng::SerializationResult serializationResult, DslModeling::Moniker moniker)\r\n    " +
        "\t{\r\n    \t\t#region Check Parameters\r\n    \t\tglobal::System.Diagnostics.Debug.Asser" +
        "t(serializationResult != null);\r\n    \t\tif (serializationResult == null)\r\n    \t\t\t" +
        "throw new global::System.ArgumentNullException(\"serializationResult\");\r\n    \t\tgl" +
        "obal::System.Diagnostics.Debug.Assert(moniker != null);\r\n    \t\tif (moniker == nu" +
        "ll)\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"moniker\");\r\n    \t\t#e" +
        "ndregion\r\n    \t\t\r\n    \t\tDslModeling::SerializationUtilities.AddMessage(\r\n    \t\t\t" +
        "serializationResult,\r\n    \t\t\tmoniker.Location,\r\n    \t\t\tDslModeling::Serializatio" +
        "nMessageKind.Error,\r\n    \t\t\tstring.Format(\r\n    \t\t\t\tglobal::System.Globalization" +
        ".CultureInfo.CurrentCulture,\r\n    \t\t\t\tResourceManager.GetString(\"UnresolvedMonik" +
        "er\"),\r\n    \t\t\t\tmoniker.MonikerName\r\n    \t\t\t),\r\n    \t\t\tmoniker.Line,\r\n    \t\t\tmoni" +
        "ker.Column\r\n    \t\t);\r\n    \t}\r\n\r\n    \t/// <summary>\r\n    \t/// Add an error for Ve" +
        "rsion mismatch.\r\n    \t/// </summary>\r\n    \t/// <param name=\"serializationContext" +
        "\">SerializationContext to add the error message to.</param>\r\n    \t/// <param nam" +
        "e=\"reader\">The reader pointing to where the message is raised.</param>\r\n    \t///" +
        " <param name=\"expectedVersion\">The version that\'s expected.</param>\r\n    \t/// <p" +
        "aram name=\"actualVersion\">Actual version from the file.</param>\r\n    \tpublic sta" +
        "tic void VersionMismatch(DslModeling::SerializationContext serializationContext," +
        " global::System.Xml.XmlReader reader, global::System.Version expectedVersion, gl" +
        "obal::System.Version actualVersion)\r\n    \t{\r\n    \t\t#region Check Parameters\r\n   " +
        " \t\tglobal::System.Diagnostics.Debug.Assert(serializationContext != null);\r\n    \t" +
        "\tif (serializationContext == null)\r\n    \t\t\tthrow new global::System.ArgumentNull" +
        "Exception(\"serializationContext\");\r\n    \t\tglobal::System.Diagnostics.Debug.Asser" +
        "t(reader != null);\r\n    \t\tif (reader == null)\r\n    \t\t\tthrow new global::System.A" +
        "rgumentNullException(\"reader\");\r\n    \t\tglobal::System.Diagnostics.Debug.Assert(e" +
        "xpectedVersion != null);\r\n    \t\tif (expectedVersion == null)\r\n    \t\t\tthrow new g" +
        "lobal::System.ArgumentNullException(\"expectedVersion\");\r\n    \t\tglobal::System.Di" +
        "agnostics.Debug.Assert(actualVersion != null);\r\n    \t\tif (actualVersion == null)" +
        "\r\n    \t\t\tthrow new global::System.ArgumentNullException(\"actualVersion\");\r\n    \t" +
        "\t#endregion\r\n    \t\t\r\n    \t\tDslModeling::SerializationUtilities.AddMessage(\r\n    " +
        "\t\t\tserializationContext,\r\n    \t\t\tDslModeling::SerializationMessageKind.Error,\r\n " +
        "   \t\t\tstring.Format(\r\n    \t\t\t\tglobal::System.Globalization.CultureInfo.CurrentCu" +
        "lture,\r\n    \t\t\t\tResourceManager.GetString(\"VersionMismatch\"), \r\n    \t\t\t\tactualVe" +
        "rsion.ToString(4), \r\n    \t\t\t\texpectedVersion.ToString(4)\r\n    \t\t\t),\r\n    \t\t\tread" +
        "er as global::System.Xml.IXmlLineInfo\r\n    \t\t);\r\n    \t}\r\n\t    #endregion\r\n\t\t\r\n\t\t" +
        "#region CustomErrors\r\n\t\t/// <summary>\r\n    \t/// Add an error for unresolved moni" +
        "ker.\r\n    \t/// </summary>\r\n    \tpublic static void UnresolvedMoniker(DslModeling" +
        "::SerializationResult serializationResult, System.Guid id)\r\n    \t{\r\n    \t\tDslMod" +
        "eling::SerializationUtilities.AddMessage(\r\n    \t\t\tserializationResult,\r\n\t\t\t\t\"\",\r" +
        "\n    \t\t\tDslModeling::SerializationMessageKind.Warning,\t// warning just for now\r\n" +
        "    \t\t\tstring.Format(\r\n    \t\t\t\tglobal::System.Globalization.CultureInfo.CurrentC" +
        "ulture,\r\n    \t\t\t\tResourceManager.GetString(\"UnresolvedMoniker\"),\r\n    \t\t\t\tid.ToS" +
        "tring()\r\n    \t\t\t),\r\n\t\t\t\t0,\r\n\t\t\t\t0\r\n    \t\t);\r\n    \t}\r\n\t\t#endregion\r\n    }\r\n}\r\n\r\nn" +
        "amespace ");

        
        #line default
        #line hidden
        
        #line 817 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Namespace));

        
        #line default
        #line hidden
        
        #line 817 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\r\n{\r\n\t/// <summary>\r\n\t/// A ModelDataSerializationPostProcessor implementation.\r\n" +
        "\t/// This is the concrete type of the double-derived implementation.\r\n\t/// </sum" +
        "mary>\r\n\tpublic sealed partial class ");

        
        #line default
        #line hidden
        
        #line 823 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 823 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationPostProcessor : DslEditorModeling::ModelDataSerializationPostProcess" +
        "or\r\n\t{\r\n\t\t#region Singleton Instance\r\n\t\t/// <summary>\r\n\t\t/// Singleton instance." +
        "\r\n\t\t/// </summary>\r\n\t\tprivate static ");

        
        #line default
        #line hidden
        
        #line 829 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 829 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(@"SerializationPostProcessor instance;
	
		/// <summary>
		/// Singleton instance.
		/// </summary>
		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]	// Will trigger creation otherwise.
		public static ");

        
        #line default
        #line hidden
        
        #line 835 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 835 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationPostProcessor Instance\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\t// No need for synchroniza" +
        "tion. Most likely running in single-thread environment, and creating an extra in" +
        "stance\r\n\t\t\t\t// doesn\'t really hurt.\r\n\t\t\t\tif (");

        
        #line default
        #line hidden
        
        #line 840 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 840 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationPostProcessor.instance == null)\r\n\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 841 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 841 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationPostProcessor.instance = new ");

        
        #line default
        #line hidden
        
        #line 841 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 841 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationPostProcessor ();\r\n\t\t\t\treturn ");

        
        #line default
        #line hidden
        
        #line 842 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 842 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationPostProcessor.instance;\r\n\t\t\t}\r\n\t\t}\r\n\t\r\n\t\t/// <summary>\r\n\t\t/// Privat" +
        "e constructor to prevent public instantiation.\r\n\t\t/// </summary>\r\n\t\tprivate ");

        
        #line default
        #line hidden
        
        #line 849 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 849 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(@"SerializationPostProcessor() : base() { }
		#endregion
	
		#region Methods
		/// <summary>
        /// Clears the gathered information.
        /// </summary>
        /// <param name=""alreadyProcessedModels"">Already reseted models.</param>
        public override void Reset(System.Collections.Generic.List<string> alreadyProcessedModels)
        {
			dictionary.Clear();
			alreadyProcessedModels.Add(""");

        
        #line default
        #line hidden
        
        #line 860 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 860 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\");\r\n");

        
        #line default
        #line hidden
        
        #line 861 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

			foreach(MetaModelLibrary m in dm.MetaModelLibraries)
			{
				if( m.ImportedLibrary == null )
					continue;

        
        #line default
        #line hidden
        
        #line 866 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\t\t\tif( !alreadyProcessedModels.Contains(\"");

        
        #line default
        #line hidden
        
        #line 867 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture((m.ImportedLibrary as MetaModel).Name));

        
        #line default
        #line hidden
        
        #line 867 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\") )\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 868 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture((m.ImportedLibrary as MetaModel).Namespace));

        
        #line default
        #line hidden
        
        #line 868 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 868 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture((m.ImportedLibrary as MetaModel).Name));

        
        #line default
        #line hidden
        
        #line 868 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationPostProcessor.Instance.Reset(alreadyProcessedModels);\r\n");

        
        #line default
        #line hidden
        
        #line 869 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

			}

        
        #line default
        #line hidden
        
        #line 871 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(@"
        }		
		
        /// <summary>
        /// Post process gathered information.
        /// </summary>
        /// <param name=""alreadyProcessedModels"">List of already processed imported models.</param>
        /// <param name=""serializationResult"">Serialization result.</param>
        /// <param name=""store"">Store.</param>		
		public override void DoPostProcess(System.Collections.Generic.List<string> alreadyProcessedModels, DslModeling::SerializationResult serializationResult, DslModeling::Store store)
		{
			base.DoPostProcess(serializationResult, store);
			
			alreadyProcessedModels.Add(""");

        
        #line default
        #line hidden
        
        #line 885 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dm.Name));

        
        #line default
        #line hidden
        
        #line 885 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\");\r\n");

        
        #line default
        #line hidden
        
        #line 886 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

			foreach(MetaModelLibrary m in dm.MetaModelLibraries)
			{
				if( m.ImportedLibrary == null )
					continue;

        
        #line default
        #line hidden
        
        #line 891 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\t\t\tif( !alreadyProcessedModels.Contains(\"");

        
        #line default
        #line hidden
        
        #line 892 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture((m.ImportedLibrary as MetaModel).Name));

        
        #line default
        #line hidden
        
        #line 892 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\") )\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 893 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture((m.ImportedLibrary as MetaModel).Namespace));

        
        #line default
        #line hidden
        
        #line 893 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 893 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture((m.ImportedLibrary as MetaModel).Name));

        
        #line default
        #line hidden
        
        #line 893 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("SerializationPostProcessor.Instance.DoPostProcess(alreadyProcessedModels, seriali" +
        "zationResult, store);\r\n");

        
        #line default
        #line hidden
        
        #line 894 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

			}

        
        #line default
        #line hidden
        
        #line 896 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"
this.Write("\t\t}\r\n\t\t#endregion\r\n\t}\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 901 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\SerializerGenerator.tt"

}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
