// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tum.PDE.ToolFramework.Templates.Shell.Model
{
    using Tum.PDE.LanguageDSL;
    using Microsoft.VisualStudio.Modeling;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System;
    
    
    #line 1 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\Shell\Model\HelpKeywordHelperGenerator.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class HelpKeywordHelperGenerator : BaseTemplate
    {
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
        public override string TransformText()
        {
            this.GenerationEnvironment = null;
            this.Write(" \r\n");
            
            #line 9 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\Shell\Model\HelpKeywordHelperGenerator.tt"

	string dslName = this.MetaModel.Name;

            
            #line default
            #line hidden
            this.Write(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace ");
            
            #line 25 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\Shell\Model\HelpKeywordHelperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.MetaModel.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\t/// <summary>\r\n\t/// Helper class used to map shapes and model elements to h" +
                    "elp keywords.\r\n\t/// </summary>\r\n\t/// <remarks>\r\n\t/// Double-derived class to all" +
                    "ow easier code customization.\r\n\t/// </remarks>\r\n\tpublic partial class ");
            
            #line 33 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\Shell\Model\HelpKeywordHelperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dslName));
            
            #line default
            #line hidden
            this.Write("HelpKeywordHelper : ");
            
            #line 33 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\Shell\Model\HelpKeywordHelperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dslName));
            
            #line default
            #line hidden
            this.Write("HelpKeywordHelperBase \r\n\t{\r\n\t\t/// <summary>\r\n\t\t/// Constructs a new ");
            
            #line 36 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\Shell\Model\HelpKeywordHelperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dslName));
            
            #line default
            #line hidden
            this.Write("HelpKeywordHelper.\r\n\t\t/// </summary>\r\n\t\tprotected ");
            
            #line 38 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\Shell\Model\HelpKeywordHelperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dslName));
            
            #line default
            #line hidden
            this.Write("HelpKeywordHelper()\r\n\t\t\t: base() { }\r\n\t\t\t\r\n\t\t/// <summary>\r\n\t\t/// Single instance" +
                    " of the ");
            
            #line 42 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\Shell\Model\HelpKeywordHelperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dslName));
            
            #line default
            #line hidden
            this.Write("HelpKeywordHelper.\r\n\t\t/// </summary>\r\n\t\tpublic static ");
            
            #line 44 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\Shell\Model\HelpKeywordHelperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dslName));
            
            #line default
            #line hidden
            this.Write(@"HelpKeywordHelper Instance
		{
			get
			{
				return null; // This DSL does not define any help keywords.
			}
		}
	}
	
	/// <summary>
	/// Helper class used to map shapes and model elements to F1 help keywords.
	/// </summary>
	public abstract class ");
            
            #line 56 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\Shell\Model\HelpKeywordHelperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dslName));
            
            #line default
            #line hidden
            this.Write("HelpKeywordHelperBase\r\n\t{\r\n\t\tprivate global::System.Collections.Generic.Dictionar" +
                    "y<string, string> helpKeywords;\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Constructs a new ");
            
            #line 61 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\Shell\Model\HelpKeywordHelperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dslName));
            
            #line default
            #line hidden
            this.Write("HelpKeywordHelperBase.\r\n\t\t/// </summary>\r\n\t\tprotected ");
            
            #line 63 "J:\Uni\CC Processes\Werkzeuge\PDE 2\Tum.PDE.ToolFramework\Tum.PDE.ToolFramework.Templates\Shell\Model\HelpKeywordHelperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dslName));
            
            #line default
            #line hidden
            this.Write("HelpKeywordHelperBase()\r\n\t\t\t: base() { }\r\n\t\t\t\r\n\t\t/// <summary>\r\n\t\t/// Called to i" +
                    "nitialize the HelpKeywords dictionary.  Derived classes may override this to add" +
                    " custom keywords to the collection.\r\n\t\t/// </summary>\r\n\t\tprotected virtual void " +
                    "Initialize()\r\n\t\t{\r\n\t\t\tthis.helpKeywords = new global::System.Collections.Generic" +
                    ".Dictionary<string, string>(0);\r\n\t\t}\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Collection of k" +
                    "ey/value pairs describing help keywords for this DSL.\r\n\t\t/// Keys are strings su" +
                    "ch as domain class names that describe elements of the DSL.\r\n\t\t/// Values are co" +
                    "rresponding help keywords.\r\n\t\t/// </summary>\r\n\t\tprotected global::System.Collect" +
                    "ions.Generic.IDictionary<string, string> HelpKeywords\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\tif" +
                    " (this.helpKeywords == null)\r\n\t\t\t\t{\r\n\t\t\t\t\tthis.helpKeywords = new global::System" +
                    ".Collections.Generic.Dictionary<string, string>(10);\r\n\t\t\t\t}\r\n\r\n\t\t\t\treturn this.h" +
                    "elpKeywords;\r\n\t\t\t}\r\n\t\t}\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Gets the help keyword associ" +
                    "ated with the given shape or model element instance.\r\n\t\t/// </summary>\r\n\t\t/// <r" +
                    "eturns>Help keyword, or empty string if there is no associated help keyword.</re" +
                    "turns>\r\n\t\tpublic virtual string GetHelpKeyword(DslModeling::ModelElement modelEl" +
                    "ement)\r\n\t\t{\r\n\t\t\tif(modelElement == null) throw new global::System.ArgumentNullEx" +
                    "ception(\"modelElement\");\r\n\t\t\t\r\n\t\t\tif(this.helpKeywords == null)\r\n\t\t\t{\r\n\t\t\t\tIniti" +
                    "alize();\r\n\t\t\t}\r\n\t\t\t\r\n\t\t\tstring helpKeyword;\r\n\t\t\tif(this.helpKeywords.TryGetValue" +
                    "(modelElement.GetType().FullName, out helpKeyword))\r\n\t\t\t{\r\n\t\t\t\treturn helpKeywor" +
                    "d;\r\n\t\t\t}\r\n\t\t\t\r\n\t\t\treturn string.Empty;\r\n\t\t}\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Gets the" +
                    " help keyword associated with the given domain role.\r\n\t\t/// </summary>\r\n\t\t/// <r" +
                    "eturns>Help keyword, or empty string if there is no associated help keyword.</re" +
                    "turns>\r\n\t\tpublic virtual string GetDomainRoleHelpKeyword(DslModeling::DomainRole" +
                    "Info domainRole)\r\n\t\t{\r\n\t\t\tif(domainRole == null) throw new global::System.Argume" +
                    "ntNullException(\"domainRole\");\r\n\t\t\t\r\n\t\t\tif(this.helpKeywords == null)\r\n\t\t\t{\r\n\t\t\t" +
                    "\tInitialize();\r\n\t\t\t}\r\n\t\t\t\r\n\t\t\tstring helpKeyword;\r\n\t\t\tif(this.helpKeywords.TryGe" +
                    "tValue(domainRole.DomainRelationship.ImplementationClass.FullName + \"/\" + domain" +
                    "Role.Name, out helpKeyword))\r\n\t\t\t{\r\n\t\t\t\treturn helpKeyword;\r\n\t\t\t}\r\n\t\t\t\r\n\t\t\tretur" +
                    "n string.Empty;\r\n\t\t}\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Gets the help keyword associate" +
                    "d with the given domain property.\r\n\t\t/// </summary>\r\n\t\t/// <returns>Help keyword" +
                    ", or empty string if there is no associated help keyword.</returns>\r\n\t\tpublic vi" +
                    "rtual string GetDomainPropertyHelpKeyword(DslModeling::DomainPropertyInfo domain" +
                    "Property)\r\n\t\t{\r\n\t\t\tif(domainProperty == null) throw new global::System.ArgumentN" +
                    "ullException(\"domainProperty\");\r\n\t\t\t\r\n\t\t\tif(this.helpKeywords == null)\r\n\t\t\t{\r\n\t\t" +
                    "\t\tInitialize();\r\n\t\t\t}\r\n\t\t\t\r\n\t\t\tstring helpKeyword;\r\n\t\t\tif(this.helpKeywords.TryG" +
                    "etValue(domainProperty.DomainClass.ImplementationClass.FullName + \"/\" + domainPr" +
                    "operty.Name, out helpKeyword))\r\n\t\t\t{\r\n\t\t\t\treturn helpKeyword;\r\n\t\t\t}\r\n\t\t\t\r\n\t\t\tret" +
                    "urn string.Empty;\r\n\t\t}\r\n\t}\r\n}\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
