//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tum.PDE.ToolFramework.Modeling.Visualization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tum.PDE.ToolFramework.Modeling.Visualization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResExtension Type conversion failed. Id: {0}, Error: {1}.
        /// </summary>
        public static string ConversionErrorMessageFormatString {
            get {
                return ResourceManager.GetString("ConversionErrorMessageFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following depenendencies are about to be deleted from the model (Warning: Embedding Relationships denote Parent-Child relationships and as such the child element is also deleted from the model).
        /// </summary>
        public static string DeletionViewModel_Description {
            get {
                return ResourceManager.GetString("DeletionViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm deletion of model element(s)....
        /// </summary>
        public static string DeletionViewModel_Titel {
            get {
                return ResourceManager.GetString("DeletionViewModel_Titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid assembly passed or assembly is not loaded..
        /// </summary>
        public static string InvalidAssemblyExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidAssemblyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Static Binding Syntax.
        /// </summary>
        public static string InvalidStaticBindingSyntax {
            get {
                return ResourceManager.GetString("InvalidStaticBindingSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the language change to take effect, please restart the application.
        /// </summary>
        public static string LanguageViewModel_LanguageChange {
            get {
                return ResourceManager.GetString("LanguageViewModel_LanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string SearchCriteriaEnum_All {
            get {
                return ResourceManager.GetString("SearchCriteriaEnum_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SearchCriteriaEnum_Name {
            get {
                return ResourceManager.GetString("SearchCriteriaEnum_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and Type.
        /// </summary>
        public static string SearchCriteriaEnum_NameAndType {
            get {
                return ResourceManager.GetString("SearchCriteriaEnum_NameAndType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string SearchCriteriaEnum_Properties {
            get {
                return ResourceManager.GetString("SearchCriteriaEnum_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties without Name.
        /// </summary>
        public static string SearchCriteriaEnum_PropertiesWithoutName {
            get {
                return ResourceManager.GetString("SearchCriteriaEnum_PropertiesWithoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string SearchCriteriaEnum_Roles {
            get {
                return ResourceManager.GetString("SearchCriteriaEnum_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SearchCriteriaEnum_Type {
            get {
                return ResourceManager.GetString("SearchCriteriaEnum_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Results.
        /// </summary>
        public static string SearchResultViewModel_FindResults {
            get {
                return ResourceManager.GetString("SearchResultViewModel_FindResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        public static string SearchSourceEnum_Elements {
            get {
                return ResourceManager.GetString("SearchSourceEnum_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements and Reference Relationships.
        /// </summary>
        public static string SearchSourceEnum_ElementsAndReferenceRelationships {
            get {
                return ResourceManager.GetString("SearchSourceEnum_ElementsAndReferenceRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Relationships.
        /// </summary>
        public static string SearchSourceEnum_ReferenceRelationships {
            get {
                return ResourceManager.GetString("SearchSourceEnum_ReferenceRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Advanced.
        /// </summary>
        public static string SearchViewModel_FindAdvanced {
            get {
                return ResourceManager.GetString("SearchViewModel_FindAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find all &apos;{0}&apos;, Source: {1}, Criteria: {2}.
        /// </summary>
        public static string SearchViewModel_OptionsSummary {
            get {
                return ResourceManager.GetString("SearchViewModel_OptionsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find all &apos;{0}&apos;, Source: {1}, Criteria: {2} and in results find &apos;{3}&apos; , Criteria: {4}.
        /// </summary>
        public static string SearchViewModel_OptionsSummaryAdv {
            get {
                return ResourceManager.GetString("SearchViewModel_OptionsSummaryAdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results found.
        /// </summary>
        public static string SearchViewModel_ResultsFound {
            get {
                return ResourceManager.GetString("SearchViewModel_ResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total elements searched.
        /// </summary>
        public static string SearchViewModel_TotalElementsSearched {
            get {
                return ResourceManager.GetString("SearchViewModel_TotalElementsSearched", resourceCulture);
            }
        }
    }
}
