# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Windows 7 box that has a 90 day trial period
  config.vm.box = "modernIE/w7-ie11"
  config.vm.hostname = "PDE"
  config.vm.provider :virtualbox do |vb|
    vb.name = "PDE"
  end  

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
     vb.gui = true
    # Customize the amount of memory on the VM:
     vb.memory = "2048"
    #Disable USB
     vb.customize ["modifyvm", :id, "--usb", "off"]
     vb.customize ["modifyvm", :id, "--usbehci", "off"]
 end

  # Run the post installation script to install the tool 
  config.vm.provision :shell, path: "scripts/Install-PDE.ps1"
  
end
